// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdzxilawrsxgvztcolyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkenhpbGF3cnN4Z3Z6dGNvbHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTkwODAsImV4cCI6MjA3MTY3NTA4MH0.0g_P0j7MRwDM3_blMmFAd2aak92qdRN4hwLUcEF4IKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});